---
- name: rebooting linux
  hosts: ubuntu
  become: yes

- tasks:
  - name: rebooting
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: waiting starting servers
    wait_for:
        host: all
        state: started
        delay: 5
        timeout: 40
    delegate_to: 127.0.0.1
